/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import repository.RP_NhanVien;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.NhanVien;
import java.sql.*;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.List;

/**
 *
 * @author admin
 */
public class NhanVienView extends javax.swing.JPanel {

    /**
     * Creates new form NhanVienView
     */
    // gọi các chức năng:= gọj mang món ăn
    private RP_NhanVien rp = new RP_NhanVien();
    // khai báo model cho bảng
    private DefaultTableModel mol = new DefaultTableModel();
    private int i = -1;// chỉ số bảng

    public NhanVienView() {
        initComponents();
        txtNgaySinh.setDateFormatString("yyyy-MM-dd");
        this.fillTable((ArrayList<NhanVien>) rp.getAll());
        loadToTableNhanVienAn();
    }

    void fillTable(ArrayList<NhanVien> list) {
        //b1: gọi model cho bảng
        mol = (DefaultTableModel) tblbang.getModel();
        // b2: xóa dl bảng cũ
        mol.setRowCount(0);
        // b3: thêm dl vào dòng trong bảng
        for (NhanVien x : list) {
            mol.addRow(new Object[]{
                x.getId(),
                x.getMaNhanVien(),
                x.getHoTen(),
                x.getGioiTinh(),
                x.getNgaySinh() != null ? new java.text.SimpleDateFormat("yyyy-MM-dd").format(x.getNgaySinh()) : "",
                x.getDiaChi(),
                x.getSoCCCD(), // Đảm bảo gọi đúng giá trị từ object
                x.getSoDienThoai(),
                x.getMatKhau(), // Không nên hiển thị mật khẩu trực tiếp vì lý do bảo mật
                x.getVaiTro(),
                x.getGhiChu()
            });
        }
    }
    
    private void loadToTableNhanVienAn() {
    DefaultTableModel model = (DefaultTableModel) tblNhanVienAn.getModel();
    model.setRowCount(0);
    List<NhanVien> list = rp.getNhanVienAn();
    for (NhanVien nv : list) {
        model.addRow(new Object[]{
            nv.getId(),
            nv.getMaNhanVien(),
            nv.getHoTen(),
            nv.getGioiTinh(),
            new SimpleDateFormat("dd/MM/yyyy").format(nv.getNgaySinh()),
            nv.getDiaChi(),
            nv.getSoCCCD(),
            nv.getSoDienThoai(),
            nv.getMatKhau(),
            nv.getVaiTro(),
            nv.getGhiChu()
        });
    }
}
    
    private NhanVien getFormData() {
    // Lấy dữ liệu từ các trường nhập liệu
    String maNhanVien = txtMaNhanVien.getText().trim();
    String hoTen = txtHoTen.getText().trim();
    String gioiTinh = rdoNam.isSelected() ? "Nam" : "Nữ"; // Kiểm tra radio button
    java.util.Date ngaySinh = txtNgaySinh.getDate(); // Lấy giá trị từ JDateChooser
    if (ngaySinh == null) {
        JOptionPane.showMessageDialog(this, "Vui lòng chọn ngày sinh!");
        return null;
    }
    String diaChi = txtDiaChi.getText().trim();
    String soCCCD = txtSoCCCD.getText().trim();
    String soDienThoai = txtSoDienThoai.getText().trim();
    String matKhau = txtMatKhau.getText().trim();
    String vaiTro = cboVaiTro.getSelectedItem().toString(); // Lấy giá trị từ combobox
    String ghiChu = txtGhiChu.getText().trim();

    // Tạo đối tượng NhanVien
    NhanVien nv = new NhanVien();
    nv.setMaNhanVien(maNhanVien);
    nv.setHoTen(hoTen);
    nv.setGioiTinh(gioiTinh);
    nv.setNgaySinh(ngaySinh); // java.util.Date
    nv.setDiaChi(diaChi);
    nv.setSoCCCD(soCCCD);
    nv.setSoDienThoai(soDienThoai);
    nv.setMatKhau(matKhau);
    nv.setVaiTro(vaiTro);
    nv.setGhiChu(ghiChu);

    return nv;
}
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        NhanVienDialog = new javax.swing.JDialog();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblNhanVienAn = new javax.swing.JTable();
        btnHienThiLaiNhanVien = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtHoTen = new javax.swing.JTextField();
        txtMaNhanVien = new javax.swing.JTextField();
        txtSoDienThoai = new javax.swing.JTextField();
        txtSoCCCD = new javax.swing.JTextField();
        cboVaiTro = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtGhiChu = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        rdoNam = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        rdoNu = new javax.swing.JRadioButton();
        btnsua = new javax.swing.JButton();
        btnan = new javax.swing.JButton();
        btnadd = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblbang = new javax.swing.JTable();
        txtseach = new javax.swing.JTextField();
        Btnseach = new javax.swing.JButton();
        btnreset = new javax.swing.JButton();
        txtDiaChi = new javax.swing.JTextField();
        txtMatKhau = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnHienThiNhanVienAn = new javax.swing.JButton();
        txtNgaySinh = new com.toedter.calendar.JDateChooser();
        jPanel4 = new javax.swing.JPanel();

        NhanVienDialog.setMinimumSize(new java.awt.Dimension(1000, 500));

        tblNhanVienAn.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        tblNhanVienAn.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Mã Nhân Viên", "Họ Và Tên", "Giới Tính", "Ngày Sinh", "Điạ Chỉ", "Số CCCD", "SDT", "Mật Khẩu", "Vai Trò", "Ghi Chú"
            }
        ));
        jScrollPane2.setViewportView(tblNhanVienAn);

        btnHienThiLaiNhanVien.setBackground(new java.awt.Color(255, 204, 204));
        btnHienThiLaiNhanVien.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnHienThiLaiNhanVien.setText("Hiển Thị Lại");
        btnHienThiLaiNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHienThiLaiNhanVienActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout NhanVienDialogLayout = new javax.swing.GroupLayout(NhanVienDialog.getContentPane());
        NhanVienDialog.getContentPane().setLayout(NhanVienDialogLayout);
        NhanVienDialogLayout.setHorizontalGroup(
            NhanVienDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NhanVienDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(NhanVienDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 988, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NhanVienDialogLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnHienThiLaiNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        NhanVienDialogLayout.setVerticalGroup(
            NhanVienDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NhanVienDialogLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btnHienThiLaiNhanVien)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel3.setText("Mã Nhân Viên");

        txtHoTen.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N

        txtMaNhanVien.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N

        txtSoDienThoai.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N

        txtSoCCCD.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N

        cboVaiTro.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        cboVaiTro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Quản Lý", "Nhân Viên" }));

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel4.setText("Họ Và Tên");

        jLabel5.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel5.setText("Ngày Sinh");

        jLabel6.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel6.setText("Số CCCD");

        jLabel7.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel7.setText("Số DT");

        jLabel8.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel8.setText("Vai Trò");

        jLabel9.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel9.setText("Địa Chỉ");

        jLabel10.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel10.setText("Ghi Chú");

        txtGhiChu.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel11.setText("Mật Khẩu");

        buttonGroup1.add(rdoNam);
        rdoNam.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        rdoNam.setText("Nam");

        jLabel12.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel12.setText("Giới Tính");

        buttonGroup1.add(rdoNu);
        rdoNu.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        rdoNu.setText("Nữ");

        btnsua.setBackground(new java.awt.Color(255, 204, 204));
        btnsua.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnsua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/raven/icon/icons8-update-20 (1).png"))); // NOI18N
        btnsua.setText("Sửa");
        btnsua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsuaActionPerformed(evt);
            }
        });

        btnan.setBackground(new java.awt.Color(255, 204, 204));
        btnan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/raven/icon/icons8-hide-20.png"))); // NOI18N
        btnan.setText("Ẩn");
        btnan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnanActionPerformed(evt);
            }
        });

        btnadd.setBackground(new java.awt.Color(255, 204, 204));
        btnadd.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnadd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/raven/icon/icons8-add-20.png"))); // NOI18N
        btnadd.setText("Thêm");
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });

        tblbang.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        tblbang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Mã Nhân Viên", "Họ Và Tên", "Giới Tính", "Ngày Sinh", "Điạ Chỉ", "Số CCCD", "SDT", "Mật Khẩu", "Vai Trò", "Ghi Chú"
            }
        ));
        tblbang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblbangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblbang);

        Btnseach.setText("Seach");
        Btnseach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnseachActionPerformed(evt);
            }
        });

        btnreset.setBackground(new java.awt.Color(255, 204, 204));
        btnreset.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnreset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/raven/icon/icons8-refresh-20.png"))); // NOI18N
        btnreset.setText("Làm Mới");
        btnreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnresetActionPerformed(evt);
            }
        });

        txtDiaChi.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N

        txtMatKhau.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel1.setText("Quản Lý Nhân Viên");

        btnHienThiNhanVienAn.setBackground(new java.awt.Color(255, 204, 204));
        btnHienThiNhanVienAn.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnHienThiNhanVienAn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/raven/icon/icons8-show-20.png"))); // NOI18N
        btnHienThiNhanVienAn.setText("Hiển Thị Nhân Viên Ẩn");
        btnHienThiNhanVienAn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHienThiNhanVienAnActionPerformed(evt);
            }
        });

        txtNgaySinh.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel1)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnadd))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(25, 25, 25)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txtSoCCCD, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtMaNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addComponent(txtNgaySinh, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(txtHoTen, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE))
                                                    .addComponent(txtSoDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(btnsua)
                                                .addGap(27, 27, 27)
                                                .addComponent(btnan)
                                                .addGap(29, 29, 29)
                                                .addComponent(btnreset)))))
                                .addGap(94, 94, 94)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel11)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(28, 28, 28)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(cboVaiTro, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtGhiChu, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(rdoNam)
                                                .addGap(35, 35, 35)
                                                .addComponent(rdoNu))))
                                    .addComponent(jLabel8))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Btnseach)
                        .addGap(18, 18, 18)
                        .addComponent(txtseach, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnHienThiNhanVienAn, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtMaNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(cboVaiTro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(txtMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel9)
                            .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(txtNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(txtGhiChu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(txtSoDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtSoCCCD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel12)
                        .addComponent(rdoNam)
                        .addComponent(rdoNu)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtseach, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Btnseach, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnadd)
                            .addComponent(btnsua)
                            .addComponent(btnan)
                            .addComponent(btnreset))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)))
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnHienThiNhanVienAn)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("")));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(302, 302, 302))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
      // Lấy dữ liệu từ form
    NhanVien nv = getFormData();
    if (nv == null) {
        return; // Nếu dữ liệu không hợp lệ (ví dụ: ngày sinh chưa chọn), thoát
    }

    // Hiển thị hộp thoại xác nhận
    int confirm = JOptionPane.showConfirmDialog(this, 
            "Bạn có chắc chắn muốn thêm nhân viên này không?", 
            "Xác nhận thêm nhân viên", 
            JOptionPane.YES_NO_OPTION);
    
    if (confirm == JOptionPane.YES_OPTION) {
        // Nếu người dùng chọn "Yes", tiến hành thêm
        int result = rp.addNhanVien(nv);
        if (result > 0) {
            JOptionPane.showMessageDialog(this, "Thêm nhân viên thành công!");
            // Cập nhật lại bảng
            fillTable((ArrayList<NhanVien>) rp.getAll());
        } else {
            JOptionPane.showMessageDialog(this, "Thêm nhân viên thất bại!");
        }
    } else {
        // Nếu người dùng chọn "No", thông báo hủy thao tác
        JOptionPane.showMessageDialog(this, "Đã hủy thao tác thêm nhân viên!");
    }
    }//GEN-LAST:event_btnaddActionPerformed

    private void tblbangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblbangMouseClicked
       // Lấy chỉ số dòng được chọn
    int selectedRow = tblbang.getSelectedRow();
    if (selectedRow == -1) {
        return; // Nếu không có dòng nào được chọn, thoát
    }

    // Lấy dữ liệu từ dòng được chọn
    String maNhanVien = tblbang.getValueAt(selectedRow, 1).toString();
    String hoTen = tblbang.getValueAt(selectedRow, 2).toString();
    String gioiTinh = tblbang.getValueAt(selectedRow, 3).toString();
    String ngaySinhStr = tblbang.getValueAt(selectedRow, 4).toString(); // Ngày sinh dạng chuỗi
    String diaChi = tblbang.getValueAt(selectedRow, 5).toString();
    String soCCCD = tblbang.getValueAt(selectedRow, 6).toString();
    String soDienThoai = tblbang.getValueAt(selectedRow, 7).toString();
    String matKhau = tblbang.getValueAt(selectedRow, 8).toString();
    String vaiTro = tblbang.getValueAt(selectedRow, 9).toString();
    String ghiChu = tblbang.getValueAt(selectedRow, 10).toString();

    // Hiển thị dữ liệu lên các trường nhập liệu
    txtMaNhanVien.setText(maNhanVien);
    txtHoTen.setText(hoTen);
    
    // Xử lý giới tính
    if (gioiTinh.equals("Nam")) {
        rdoNam.setSelected(true);
    } else {
        rdoNu.setSelected(true);
    }

    // Xử lý ngày sinh (chuyển từ chuỗi sang java.util.Date để gán vào JDateChooser)
    try {
        if (!ngaySinhStr.isEmpty()) {
            java.util.Date ngaySinh = new java.text.SimpleDateFormat("yyyy-MM-dd").parse(ngaySinhStr);
            txtNgaySinh.setDate(ngaySinh); // JDateChooser sẽ tự động hiển thị theo định dạng "yyyy-MM-dd"
        } else {
            txtNgaySinh.setDate(null); // Nếu không có ngày sinh, đặt JDateChooser về null
        }
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Lỗi khi hiển thị ngày sinh!");
    }

    // Hiển thị các trường còn lại
    txtDiaChi.setText(diaChi);
    txtSoCCCD.setText(soCCCD);
    txtSoDienThoai.setText(soDienThoai);
    txtMatKhau.setText(matKhau);
    cboVaiTro.setSelectedItem(vaiTro);
    txtGhiChu.setText(ghiChu);

    }//GEN-LAST:event_tblbangMouseClicked

    private void BtnseachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnseachActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_BtnseachActionPerformed

    private void btnresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnresetActionPerformed
        // Đặt lại các trường nhập liệu về trạng thái mặc định
    txtMaNhanVien.setText("");
    txtHoTen.setText("");
    
    // Đặt lại giới tính (chọn mặc định là "Nam" hoặc bỏ chọn cả hai)
    rdoNam.setSelected(true); // Mặc định chọn "Nam"
    rdoNu.setSelected(false);
    
    // Đặt lại ngày sinh
    txtNgaySinh.setDate(null); // Xóa ngày sinh trong JDateChooser
    
    // Đặt lại các trường còn lại
    txtDiaChi.setText("");
    txtSoCCCD.setText("");
    txtSoDienThoai.setText("");
    txtMatKhau.setText("");
    
    // Đặt lại vai trò (chọn mục đầu tiên trong JComboBox hoặc một giá trị mặc định)
    if (cboVaiTro.getItemCount() > 0) {
        cboVaiTro.setSelectedIndex(0); // Chọn mục đầu tiên
    }
    
    txtGhiChu.setText("");
    tblbang.clearSelection();
    }//GEN-LAST:event_btnresetActionPerformed

    private void btnsuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsuaActionPerformed
        // Kiểm tra xem có dòng nào được chọn trong bảng không
    int selectedRow = tblbang.getSelectedRow();
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Vui lòng chọn nhân viên cần sửa!");
        return;
    }

    // Lấy ID của nhân viên từ bảng
    int id = (int) tblbang.getValueAt(selectedRow, 0);

    // Lấy dữ liệu từ form
    NhanVien nv = getFormData();
    if (nv == null) {
        return; // Nếu dữ liệu không hợp lệ (ví dụ: ngày sinh chưa chọn), thoát
    }

    // Gán ID cho đối tượng NhanVien
    nv.setId(id);

    // Hiển thị hộp thoại xác nhận
    int confirm = JOptionPane.showConfirmDialog(this, 
            "Bạn có chắc chắn muốn cập nhật thông tin nhân viên này không?", 
            "Xác nhận cập nhật nhân viên", 
            JOptionPane.YES_NO_OPTION);
    
    if (confirm == JOptionPane.YES_OPTION) {
        // Nếu người dùng chọn "Yes", tiến hành cập nhật
        int result = rp.updateNhanVien(nv);
        if (result > 0) {
            JOptionPane.showMessageDialog(this, "Cập nhật nhân viên thành công!");
            // Cập nhật lại bảng
            fillTable((ArrayList<NhanVien>) rp.getAll());
        } else {
            JOptionPane.showMessageDialog(this, "Cập nhật nhân viên thất bại!");
        }
    } else {
        // Nếu người dùng chọn "No", thông báo hủy thao tác
        JOptionPane.showMessageDialog(this, "Đã hủy thao tác cập nhật nhân viên!");
    }
    }//GEN-LAST:event_btnsuaActionPerformed

    private void btnanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnanActionPerformed
         int row = tblbang.getSelectedRow();
    if (row == -1) {
        JOptionPane.showMessageDialog(this, "Vui lòng chọn nhân viên để ẩn");
        return;
    }

    int id = (int) tblbang.getValueAt(row, 0);
    String ten = (String) tblbang.getValueAt(row, 2); // Cột tên nhân viên

    int confirm = JOptionPane.showConfirmDialog(
        this,
        "Bạn có chắc chắn muốn ẩn nhân viên: " + ten + "?",
        "Xác nhận ẩn nhân viên",
        JOptionPane.YES_NO_OPTION
    );

    if (confirm == JOptionPane.YES_OPTION) {
        if (rp.anNhanVien(id)) {
            JOptionPane.showMessageDialog(this, "Đã ẩn nhân viên thành công");
            this.fillTable((ArrayList<NhanVien>) rp.getAll());
            loadToTableNhanVienAn();
        } else {
            JOptionPane.showMessageDialog(this, "Ẩn nhân viên thất bại");
        }
    }
    }//GEN-LAST:event_btnanActionPerformed

    private void btnHienThiNhanVienAnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHienThiNhanVienAnActionPerformed
        NhanVienDialog.setLocationRelativeTo(null);
        NhanVienDialog.setVisible(true);
    }//GEN-LAST:event_btnHienThiNhanVienAnActionPerformed

    private void btnHienThiLaiNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHienThiLaiNhanVienActionPerformed
        int row = tblNhanVienAn.getSelectedRow();
    if (row == -1) {
        JOptionPane.showMessageDialog(this, "Chọn nhân viên để hiển thị lại");
        return;
    }

    int id = (int) tblNhanVienAn.getValueAt(row, 0);
    String ten = (String) tblNhanVienAn.getValueAt(row, 2); // Cột tên nhân viên

    int confirm = JOptionPane.showConfirmDialog(
        this,
        "Bạn có chắc chắn muốn hiển thị lại nhân viên: " + ten + "?",
        "Xác nhận hiển thị lại",
        JOptionPane.YES_NO_OPTION
    );

    if (confirm == JOptionPane.YES_OPTION) {
        if (rp.hienThiLaiNhanVien(id)) {
            JOptionPane.showMessageDialog(this, "Đã hiển thị lại nhân viên");
            this.fillTable((ArrayList<NhanVien>) rp.getAll());
            loadToTableNhanVienAn(); // Load lại bảng nhân viên ẩn
        } else {
            JOptionPane.showMessageDialog(this, "Hiển thị lại thất bại");
        }
    }
    }//GEN-LAST:event_btnHienThiLaiNhanVienActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btnseach;
    private javax.swing.JDialog NhanVienDialog;
    private javax.swing.JButton btnHienThiLaiNhanVien;
    private javax.swing.JButton btnHienThiNhanVienAn;
    private javax.swing.JButton btnadd;
    private javax.swing.JButton btnan;
    private javax.swing.JButton btnreset;
    private javax.swing.JButton btnsua;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> cboVaiTro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton rdoNam;
    private javax.swing.JRadioButton rdoNu;
    private javax.swing.JTable tblNhanVienAn;
    private javax.swing.JTable tblbang;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtGhiChu;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JTextField txtMaNhanVien;
    private javax.swing.JTextField txtMatKhau;
    private com.toedter.calendar.JDateChooser txtNgaySinh;
    private javax.swing.JTextField txtSoCCCD;
    private javax.swing.JTextField txtSoDienThoai;
    private javax.swing.JTextField txtseach;
    // End of variables declaration//GEN-END:variables


}
